version: '3'
services:
  mongodb:
    image: 'mongo'
    ports:
      - '27017:27017'
    volumes:
      - ~/data/db:/data/db

  cassandra:
    image: 'cassandra'
    ports:
      - '7000:7000'
      - '7001:7001'
      - '7199:7199'
      - '9042:9042'
      - '9160:9160'
    volumes:
      - ~/cassandra/data:/var/lib/cassandra
